#!/usr/bin/env bash
set -x

if [ "$CI" = true ]; then
  exec ./node_modules/.bin/mocha \
    --require ts-node/register \
    --full-trace \
    --exit \
    'src/test/helpers/setup.ts' \
    'src/**/*.test.ts'
fi

exec ./node_modules/.bin/mocha \
  --inspect=9241 \
  --require ts-node/register \
  --full-trace \
  --watch \
  --watch-extensions ts,tsx,js,jsx,json \
  'src/test/helpers/setup.ts' \
  'src/**/*.test.ts'